receitas/urls.py
from django.conf.urls import url
from . import views

app_name = 'receitas'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # /music/album/add/
    url(r'prescricao/add/$', views.AlbumCreate.as_view(), name='album-add'),
]

webclaudio/urls.py
from django.conf.urls import include, url
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^receitas/', include('receitas.urls')),
]

receitas/models.py
from django.db import models
from django.core.urlresolvers import reverse



#class Song(models.Model):
class Remedio(models.Model):
    nome_remedio = models.CharField(max_length=250, default='()_Sem Remédio')
    texto_remedio = models.TextField()
    #is_favorite = models.BooleanField(default=False)


    def __str__(self):
        return self.nome_remedio

#class Album(models.Model):
class Prescricao(models.Model):
    nome_medico = models.CharField(max_length=250)
    data_ano_mes_dia = models.CharField(max_length=8)
    data_mes_texto = models.CharField(max_length=25)
    texto_receita = models.TextField()

    # ----------------------------------------------------------------

    remedio1 = models.ForeignKey(Remedio, related_name="remedio1s", null=True)

    def save(self, *args, **kwargs):
        if self.remedio1 is None:  # Set default reference
            self.remedio1 = Remedio.objects.get(id=1)
        super(Prescricao, self).save(*args, **kwargs)

    # ----------------------------------------------------------------

    remedio2 = models.ForeignKey(Remedio, related_name="remedio2s", null=True)

    def save(self, *args, **kwargs):
        if self.remedio2 is None:  # Set default reference
            self.remedio2 = Remedio.objects.get(id=1)
        super(Prescricao, self).save(*args, **kwargs)

    # ----------------------------------------------------------------

    remedio3 = models.ForeignKey(Remedio, related_name="remedio3s", null=True)

    def save(self, *args, **kwargs):
        if self.remedio3 is None:  # Set default reference
            self.remedio3 = Remedio.objects.get(id=1)
        super(Prescricao, self).save(*args, **kwargs)

    # ----------------------------------------------------------------

    remedio4 = models.ForeignKey(Remedio, related_name="remedio4s", null=True)

    def save(self, *args, **kwargs):
        if self.remedio4 is None:  # Set default reference
            self.remedio4 = Remedio.objects.get(id=1)
        super(Prescricao, self).save(*args, **kwargs)

    # ----------------------------------------------------------------

    remedio5 = models.ForeignKey(Remedio, related_name="remedio5s", null=True)

    def save(self, *args, **kwargs):
        if self.remedio5 is None:  # Set default reference
            self.remedio5 = Remedio.objects.get(id=1)
        super(Prescricao, self).save(*args, **kwargs)

    # ----------------------------------------------------------------

    remedio6 = models.ForeignKey(Remedio, related_name="remedio6s", null=True)

    def save(self, *args, **kwargs):
        if self.remedio6 is None:  # Set default reference
            self.remedio6 = Remedio.objects.get(id=1)
        super(Prescricao, self).save(*args, **kwargs)

    # ----------------------------------------------------------------

    remedio7 = models.ForeignKey(Remedio, related_name="remedio7s", null=True)

    def save(self, *args, **kwargs):
        if self.remedio7 is None:  # Set default reference
            self.remedio7 = Remedio.objects.get(id=1)
        super(Prescricao, self).save(*args, **kwargs)

    # ----------------------------------------------------------------

    remedio8 = models.ForeignKey(Remedio, related_name="remedio8s", null=True)

    def save(self, *args, **kwargs):
        if self.remedio8 is None:  # Set default reference
            self.remedio8 = Remedio.objects.get(id=1)
        super(Prescricao, self).save(*args, **kwargs)

    # ----------------------------------------------------------------

    def get_absolute_url(self):
        return reverse('receitas:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.data_mes_texto + ' - ' + self.nome_medico

receitas/forms.py
from django.contrib.auth.models import User
from django import forms
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

receitas/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login

from django.views import generic
from django.views.generic import View
from .models import Prescricao
from .forms import UserForm

class IndexView(generic.ListView):
    template_name = 'receitas/index.html'
    context_object_name = 'all_prescricoes'

    def get_queryset(self):
        return Prescricao.objects.all()

class DetailView(generic.DetailView):
    model = Prescricao
    template_name = 'receitas/detail.html'

class AlbumCreate(CreateView):
    model = Prescricao
    fields = ['nome_medico', 'data_ano_mes_dia', 'data_mes_texto', 'texto_receita']


class UserFormView(View):
    form_class = UserForm
    template_name = 'receitas/registration_form.html'
    # mostra um formulário "em branco"
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # processando dados do formulário
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # dados limpos (normalizados)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #retorna objetos "User" (se os dados estiverem corretos)
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('receitas:index')

        return render(request, self.template_name, {'form': form})

receitas/templates/receitas/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}RepoMed Lista{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'receitas/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <! -- nav class="navbar navbar-default" -->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class ="icon-bar"></span>
                    <span class ="icon-bar"></span>
                    <span class ="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'receitas:index' %}">RepoMed</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id ="topNavBar">

                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'receitas:index' %}">
                            <span class="glyphicon glyphicon-tint"></span>&nbsp; Prescrições
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'receitas:album-add' %}">
                            <span class="glyphicon glyphicon-pencil"></span>&nbsp; Nova Prescrição
                        </a>
                    </li>

                </ul>

                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Buscar</button>
                </form>

                {% if user.is_authenticated %}
                    <a href="/receitas/register/">Criar / Alterar Conta</a>
                {% endif %}



                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="http://127.0.0.1:8000/admin/receitas/prescricao/">
                            <span class="glyphicon glyphicon-list-alt"></span>&nbsp; Administrar
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'receitas:index' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Sair
                        </a>
                    </li>

                </ul>

            </div>

        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

receitas/templates/receitas/detail.html
{% extends 'receitas/base.html' %}
{% block title %}RepoMed Receita{% endblock %}

{% block body %}
    <h3>{{ prescricao }} :</h3>{{ prescricao.texto_receita }}<br><p></p><br><p></p>
    {% if prescricao.remedio1.nome_remedio != '()_Sem Remédio' %}<li>
        <b>{{ prescricao.remedio1.nome_remedio }}  </b><br><p>{{ prescricao.remedio1.texto_remedio }}</p><br></li>
    {% endif %}
    {% if prescricao.remedio2.nome_remedio != '()_Sem Remédio' %}<li>
        <b>{{ prescricao.remedio2.nome_remedio }}  </b><br><p>{{ prescricao.remedio2.texto_remedio }}</p><br></li>
    {% endif %}
    {% if prescricao.remedio3.nome_remedio != '()_Sem Remédio' %}<li>
        <b>{{ prescricao.remedio3.nome_remedio }}  </b><br><p>{{ prescricao.remedio3.texto_remedio }}</p><br></li>
    {% endif %}
    {% if prescricao.remedio4.nome_remedio != '()_Sem Remédio' %}<li>
        <b>{{ prescricao.remedio4.nome_remedio }}  </b><br><p>{{ prescricao.remedio4.texto_remedio }}</p><br></li>
    {% endif %}
    {% if prescricao.remedio5.nome_remedio != '()_Sem Remédio' %}<li>
        <b>{{ prescricao.remedio5.nome_remedio }}  </b><br><p>{{ prescricao.remedio5.texto_remedio }}</p><br></li>
    {% endif %}
    {% if prescricao.remedio6.nome_remedio != '()_Sem Remédio' %}<li>
        <b>{{ prescricao.remedio6.nome_remedio }}  </b><br><p>{{ prescricao.remedio6.texto_remedio }}</p><br></li>
    {% endif %}
    {% if prescricao.remedio7.nome_remedio != '()_Sem Remédio' %}<li>
        <b>{{ prescricao.remedio7.nome_remedio }}  </b><br><p>{{ prescricao.remedio7.texto_remedio }}</p><br></li>
    {% endif %}
    {% if prescricao.remedio8.nome_remedio != '()_Sem Remédio' %}<li>
        <b>{{ prescricao.remedio8.nome_remedio }}  </b><br><p>{{ prescricao.remedio8.texto_remedio }}</p><br></li>
    {% endif %}
{% endblock %}

receitas/templates/receitas/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

receitas/templates/receitas/index.html
{% extends 'receitas/base.html' %}

{% block body %}
    {% if all_prescricoes %}
        <h3>Minhas Prescrições:</h3>
        <ul>
            {% for prescricao in all_prescricoes %}
            <li><a href="{% url 'receitas:detail' prescricao.id %}">{{ prescricao.nome_medico }} (de {{ prescricao.data_mes_texto }})</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>Você não possui nenhuma receita!</h3>
    {% endif %}
{% endblock %}

receitas/templates/receitas/prescricao_form.html
{% extends 'receitas/base.html' %}
{% block title %}Nova Prescrição{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class = "panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'receitas/form-template.html' %}
                        <div class ="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Enviar</button>

                            </div>

                        </div>

                    </form>

                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

receitas/templates/receitas/registration_form.html
{% extends 'receitas/base.html' %}
{% block title %}Registro{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class = "panel-body">
                    <h4>Criar nova Conta de Usuário (o e-mail é opcional)</h4>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'receitas/form-template.html' %}
                        <div class ="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Enviar</button>

                            </div>

                        </div>

                    </form>

                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

receitas/templates/receitas/sair.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OBRIGADO!</title>
</head>
<body>

</body>
</html>